import { describe, expect, it } from "vitest";
import type { AnalysisRun, AnalysisRunStage } from "citation-fidelity/ui-contract";

import { buildStageCommand } from "../lib/run-command-builder";

const run: AnalysisRun = {
  id: "run-1",
  seedDoi: "10.1234/seed",
  trackedClaim: "Tracked claim",
  targetStage: "m6-llm-judge",
  status: "queued",
  currentStage: undefined,
  runRoot: "/tmp/runs/run-1",
  config: {
    stopAfterStage: "m6-llm-judge",
    forceRefresh: true,
    m5TargetSize: 40,
    m6Model: "claude-opus-4-6",
    m6Thinking: true,
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

const stages: AnalysisRunStage[] = [
  {
    runId: run.id,
    stageKey: "pre-screen",
    stageOrder: 1,
    status: "succeeded",
    inputArtifactPath: undefined,
    primaryArtifactPath: "/tmp/runs/run-1/01-pre-screen/2026-04-04_001_pre-screen-results.json",
    reportArtifactPath: undefined,
    manifestPath: undefined,
    logPath: undefined,
    summary: undefined,
    errorMessage: undefined,
    startedAt: undefined,
    finishedAt: undefined,
    exitCode: undefined,
    processId: undefined,
  },
  {
    runId: run.id,
    stageKey: "m2-extract",
    stageOrder: 2,
    status: "succeeded",
    inputArtifactPath: undefined,
    primaryArtifactPath: "/tmp/runs/run-1/02-m2-extract/2026-04-04_001_m2-extraction-results.json",
    reportArtifactPath: undefined,
    manifestPath: undefined,
    logPath: undefined,
    summary: undefined,
    errorMessage: undefined,
    startedAt: undefined,
    finishedAt: undefined,
    exitCode: undefined,
    processId: undefined,
  },
  {
    runId: run.id,
    stageKey: "m3-classify",
    stageOrder: 3,
    status: "succeeded",
    inputArtifactPath: undefined,
    primaryArtifactPath: "/tmp/runs/run-1/03-m3-classify/2026-04-04_001_classification-results.json",
    reportArtifactPath: undefined,
    manifestPath: undefined,
    logPath: undefined,
    summary: undefined,
    errorMessage: undefined,
    startedAt: undefined,
    finishedAt: undefined,
    exitCode: undefined,
    processId: undefined,
  },
  {
    runId: run.id,
    stageKey: "m4-evidence",
    stageOrder: 4,
    status: "succeeded",
    inputArtifactPath: undefined,
    primaryArtifactPath: "/tmp/runs/run-1/04-m4-evidence/2026-04-04_001_evidence-results.json",
    reportArtifactPath: undefined,
    manifestPath: undefined,
    logPath: undefined,
    summary: undefined,
    errorMessage: undefined,
    startedAt: undefined,
    finishedAt: undefined,
    exitCode: undefined,
    processId: undefined,
  },
  {
    runId: run.id,
    stageKey: "m5-adjudicate",
    stageOrder: 5,
    status: "succeeded",
    inputArtifactPath: undefined,
    primaryArtifactPath: "/tmp/runs/run-1/05-m5-adjudicate/2026-04-04_001_calibration-set.json",
    reportArtifactPath: undefined,
    manifestPath: undefined,
    logPath: undefined,
    summary: undefined,
    errorMessage: undefined,
    startedAt: undefined,
    finishedAt: undefined,
    exitCode: undefined,
    processId: undefined,
  },
  {
    runId: run.id,
    stageKey: "m6-llm-judge",
    stageOrder: 6,
    status: "not_started",
    inputArtifactPath: undefined,
    primaryArtifactPath: undefined,
    reportArtifactPath: undefined,
    manifestPath: undefined,
    logPath: undefined,
    summary: undefined,
    errorMessage: undefined,
    startedAt: undefined,
    finishedAt: undefined,
    exitCode: undefined,
    processId: undefined,
  },
];

describe("buildStageCommand", () => {
  it("builds the documented m6 command shape", () => {
    const command = buildStageCommand(run, stages, "m6-llm-judge");

    expect(command.args).toEqual([
      "m6-llm-judge",
      "--calibration",
      "/tmp/runs/run-1/05-m5-adjudicate/2026-04-04_001_calibration-set.json",
      "--model",
      "claude-opus-4-6",
      "--thinking",
      "--output",
      expect.stringContaining("/06-m6-llm-judge"),
    ]);
  });
});
